### ISSUE TITLE
"List is not callable" error during deploy

### ISSUE THREAD

**Issue by johnsca** [jamesbeedy/layer-puppet-agent#2]
The `puppet_purge` method added in [96640f](https://github.com/jamesbeedy/layer-puppet-agent/commit/96640f5ef94b8f370e29a5e754485d4016d967cc#diff-7dc9136d8694e28ee629b79a63751328R78) gets overwritten by [the list in the init method](https://github.com/jamesbeedy/layer-puppet-agent/blob/master/lib/charms/layer/puppet.py#L49) leading to an error during deployment.

**Comment by jamesbeedy** [comment]
@johnsca thanks! Good looking out! 
Fixed in c47759f7ac258543f67df2c755fc34755b48ab45

**Comment by jamesbeedy** [comment]
Err ... working on a complete fix now.

**Comment by jamesbeedy** [comment]
@johnsca this is fixed
